name: Deploy Site on WordPress Post Update
# Ejecuta el workflow cuando se dispare un evento repository_dispatch.
on:
  workflow_dispatch:  # También puedes correrlo manualmente
  repository_dispatch:
    types: [new_post, update_post]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Chequear el código del repositorio.
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Instalar las dependencias del proyecto (en caso de usar npm).
    - name: Install dependencies
      run: npm install

    # 3. Ejecutar el build del proyecto Astro.
    - name: Build site
      run: npm run build

    # 4. Desplegar los archivos generados al servidor usando FTP.
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/ # El directorio generado después del build de Astro
        server-dir: /public_html/  # La carpeta donde se va a desplegar en cPanel
